language: generic

#Anytime we use docker, we're using ourselves super user permissions
sudo: required

services:
  #telling travis CI to automatically install a copy of docker into our running container
  - docker

before_install:
  #below is the command that should be executed to build our docker image  using Dockerfile.dev in our current working directory using "."
  #also providing it a tag name using -t of "hjmok/docker-react" so we don't have to worry about a long ID
  - docker build -t hjmok/docker-react -f Dockerfile.dev .

#script section contains all the commands needed to run the test suites
script:
  - docker run -e CI=true hjmok/docker-react npm run test

#this section tells how to take the travis CI configuration and deploy it to AWS
deploy:
  #travis CI already has elasticbeanstalk instructions built in
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-909807248326"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
